[package]
name = "multipart-async"

version = "0.0.2"

authors = ["Austin Bonander <austin.bonander@gmail.com>"]

description = "A backend-agnostic extension for asynchronous HTTP libraries that provides support for POST multipart/form-data requests on for both client and server."

keywords = ["form-data", "hyper", "async", "http", "upload"]

repository = "http://github.com/abonander/multipart-async"

license = "MIT OR Apache-2.0"

[dependencies]
bytes = "0.4.4"
display_bytes = "0.1"
env_logger = "0.3"
futures = "0.1"
http = "0.1.0"
log = "0.3"
mime = "0.3"
mime_guess = "2.0.0-alpha.1"
rand = "0.3"
tempdir = "0.3"
buf_redux = "0.6.1"

hyper = { version = "0.11", optional = true }
httparse = { version = "1.0", optional = true }
twoway = { version = "0.1", optional = true }

[features]
client = []
default = ["hyper", "server", "client"]
server = ["twoway", "httparse"]
sse4 = ["twoway/pcmp"]
# Use `Arc` instead of `Rc` where needed
use_arc = []

[[bin]]
name = "form_test"
path = "bin/form_test.rs"
required-features = ["hyper", "server"]
